sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: iYEth96xVGddSWH1MkZH4IIu01cw5hf7p9C5+5H4e+1IqPFCrOR0MzRKDMqCjULKeHxiss3lWKYXX3RlWHXmN/wohJpVhWzght6k1mOzuwi53dMlYL8h0shQBOSnPIoG1wKZZYJnwT8Ondm67lmZ3Iv08tQrwAUvRq2BWNBWUEoumGa6OCdMf22l8sxvE+L1qoYvkOLY+a4UEBoNLe6vv3mPWO8Yo0G21KFKZqHGEMl76L0kXH8FGC4PFK9Aj4yzItZOTT/keCWDkFgo8u7ug2WeLbSAk+YJXbAUPPfkQt2c2nTXz7XZPbfO6Q32hzNMqNxx9aObs5Gym45cJPf03EK1XrUx9vo7NdTLXiwjJkGuBugyZHHneiQj1GJ2SzA4hL6qXDTCsLpT69Q9GuimpStQBAGyxpBPZjF+TV6zvcRfMQQw6DMBsA3wUQCzcNm3q3DHrGeoJJGrUG+mSZXH0V40i1/JrWUZK1Ti9pnxiQPr6BS9cV9nfPTE5G5yuRsOu+/ZJ9TmRwQ/w2NhqgBLDQisnC0W6BJJ7/qLqO+bmLkcxYAbVzZkVBX/jiW8NuCfIBZp6kMmPvBH33fb2gsdL/AVEqOP2g7mzbgJizSDt/F4mOjVHIzSsXpuzi2ST38HNOR5ZV8r+Xao9h4thavxNc0ME26ddRX//aY4AJPTzxc=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Christopher-Columbus-and-the-New-World-of-His-Discovery---Volume-3_4110
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy